//AMS_MASTER______main_header

//CAN2_BAUDRATE------>500KBPS
#define CAN_USE_EXTENDED_ID   FALSE
#DEFINE CAN_BRG_PRESCALAR 1
#DEFINE CAN_BRG_SYNCH_JUMP_WIDTH 0
#DEFINE CAN_BRG_PROPAGATION_TIME 0
#DEFINE CAN_BRG_PHASE_SEGMENT_1 4
#DEFINE CAN_BRG_SAM 0
#DEFINE CAN_BRG_SEG_2_PHASE_TS 1
#DEFINE CAN_BRG_PHASE_SEGMENT_2 2
#DEFINE CAN_BRG_WAKE_FILTER 0
#DEFINE CAN_CANCKS 0
//CAN2_BAUDRATE------>500KBPS
#define CAN2_USE_EXTENDED_ID   FALSE
#DEFINE CAN2_BRG_PRESCALAR 1 // UN 0 PARA UN MEGAHERCIO..............UN 2 PARA 250 KHZ
#DEFINE CAN2_BRG_SYNCH_JUMP_WIDTH 0 
#DEFINE CAN2_BRG_PROPAGATION_TIME 0
#DEFINE CAN2_BRG_PHASE_SEGMENT_1 4
#DEFINE CAN2_BRG_SAM 0
#DEFINE CAN2_BRG_SEG_2_PHASE_TS 1
#DEFINE CAN2_BRG_PHASE_SEGMENT_2 2
#DEFINE CAN2_BRG_WAKE_FILTER 0
#DEFINE CAN2_CANCKS 0

#include <24EP512GU810.h>
#device ICSP=1
#device ADC=8
#use delay(crystal=20000000)

#FUSES PR
#FUSES HS                        //High frec. oscilator selection, as we have a 20MHz osc. HS is the fuse needed
#FUSES NOWDT                    //No Watch Dog Timer
#FUSES CKSFSM                   //Clock Switching is enabled, fail Safe clock monitor is enabled
#FUSES NOBROWNOUT               //No brownout reset
#FUSES NOJTAG                   //JTAG disabled

#use FIXED_IO( E_outputs=PIN_E8,PIN_E7 )

#define LED_1   PIN_E7
#define LED_0   PIN_E8




